version: '3.7'
services:

  clouddrive:
    image: wsiz/clouddrive:0.0.3
    deploy:
      replicas: 6
      resources:
        limits:
          cpus: "1.0"
          memory: 100M

      restart_policy:
        condition: on-failure

    ports:
      - "4001:4001"

    networks:
      - net1

networks:
  net1: